#!/bin/bash

# Obtener la lista de archivos HTML en el directorio actual
html_files=$(find . -maxdepth 1 -type f -name "*.html")

# Iterar sobre cada archivo HTML encontrado
for file in $html_files; do
    # Extraer el nombre del archivo
    filename=$(basename "$file")

    # Verificar si el archivo ya existe en el directorio padre
    if [ -e "../$filename" ]; then
        # Obtener la fecha de modificación del archivo en el directorio actual
        current_modification=$(stat -c %Y "$file")

        # Obtener la fecha de modificación del archivo en el directorio padre
        parent_modification=$(stat -c %Y "../$filename")

        # Comparar las fechas de modificación para determinar si el archivo es más reciente
        if [ $current_modification -gt $parent_modification ]; then
            # Copiar el archivo al directorio padre
            cp "$file" ..
            echo "Copied $filename to parent directory"
        else
            echo "$filename already exists and is up to date in parent directory"
        fi
    else
        # Copiar el archivo al directorio padre
        cp "$file" ..
        echo "Copied $filename to parent directory"
    fi
done

